---
title: "06.1-MappingCensusBasic"
output: 
  md_document:
    variant: gfm
  html_document:
    toc: true
date: "2025-03-27"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# Census Mapping

```{r}
library(tidycensus)
options(tigris_use_cache = T)
```

```{r}
nm_income <- get_acs(
  geography = "tract", 
  state = "NM", 
  variables = "B19013_001", 
  year = 2020, 
  geometry = T
)
nm_income
```

## Basic plotting

```{r}
plot(nm_income['estimate'])
```

## ggplot2

### Cholopleth

```{r}
library(tidycensus)
library(tidyverse)
library(tigris)
```

```{r}
us_median_age <- get_acs(
  geography = "state", 
  variables = "B01002_001",
  year = 2019,
  survey = "acs1",
  geometry = T,
  resolution = "20m",
) |> 
  shift_geometry()

plot(us_median_age$geometry)
```

```{r}
ggplot(us_median_age, aes(fill = estimate)) +
  geom_sf() +
  labs(title = "Median Age by State, 2019", 
       caption = "Data Source US Census Bureau 1-year ACS", 
       fill = "ACS estimate") +
  scale_fill_distiller(palette = "RdPu", 
                       direction = 1) +
  theme_void()
```

## tmap

```{r}
bernalillo_race <- get_decennial(
  geography = "tract", 
  state = "NM", 
  county = "Bernalillo",
  variables = c(
    Hispanic = "P2_002N",
    White = "P2_005N",
    Black = "P2_006N",
    Native = "P2_007N",
    Asian = "P2_008N"    
  ),
  summary_var = "P2_001N",
  year = 2020,
  geometry = T
) |> 
  mutate(percent = 100 * value / summary_value)
bernalillo_race
```

### Chorpleth with tmap

```{r}
library(tmap)
bernalillo_hisp <- bernalillo_race |> 
  filter(variable == "Hispanic")
bernalillo_hisp

tm_shape(bernalillo_hisp) +
  tm_polygons(fill = "percent")
```

```{r}
hist(bernalillo_hisp$percent)
```

```{r}
bernalillo_asian <- bernalillo_race |> 
  filter(variable == "Asian")

tm_shape(bernalillo_asian) +
  tm_polygons(fill = "percent")
```

```{r}
hist(bernalillo_asian$percent)
```

```{r}
tm_shape(bernalillo_asian) +
  tm_polygons(fill = "percent", 
              style = "quantile", 
              n = 5, 
              palette = "Greens", 
              title = "2020 US Census") +
  tm_layout(title = "Percent Asian\n by Census Tract",
            frame = F, legend.outside = T)
```

```{r}
tm_shape(bernalillo_asian) + 
  tm_polygons(col = "percent",
          style = "jenks",
          n = 5,
          palette = "Purples",
          title = "2020 US Census",
          legend.hist = TRUE) + 
  tm_layout(title = "Percent Asian\nby Census tract",
            frame = FALSE,
            legend.outside = TRUE,
            bg.color = "grey70",
            legend.hist.width = 5,
            fontfamily = "Verdana")
```

## Reference elements

```{r}
library(mapboxapi)

readRenviron("~/.Renviron")
```

```{r}
bernalillo_tiles <- get_static_tiles(
  location = bernalillo_hisp, 
  zoom = 10,
  style_id = "light-v9",
  username = "mapbox"
)
```

```{r}
tm_shape(bernalillo_tiles) + 
  tm_rgb() + 
  tm_shape(bernalillo_hisp) + 
  tm_polygons(col = "percent",
          style = "jenks",
          n = 5,
          palette = "Greens",
          title = "2020 US Census",
          alpha = 0.5) +
  tm_layout(title = "Percent Hispanic\nby Census tract",
            legend.outside = TRUE,
            fontfamily = "Verdana") + 
  tm_scale_bar(position = c("left", "bottom")) + 
  tm_compass(position = c("right", "top")) + 
  tm_credits("(c) Mapbox, OSM    ", 
             bg.color = "white",
             position = c("RIGHT", "BOTTOM"))
```

## Graduated symbols

```{r}
tm_shape(bernalillo_hisp) + 
  tm_polygons() + 
  tm_bubbles(size = "value", alpha = 0.5, 
             col = "navy",
             title.size = "Hispanic - 2020 US Census") + 
  tm_layout(legend.outside = TRUE,
            legend.outside.position = "bottom")
```

## Faceted maps

```{r}
tm_shape(bernalillo_race) + 
  tm_facets(by = "variable", scale.factor = 4) + 
  tm_polygons(fill = "percent",
          fill.scale = tm_scale_intervals(
            style = "jenks",
            #pal = "brewer.blues",
            n = 6
          ),
          #n = 6,
          #palette = "brewer.blues",
          fill.legend = tm_legend("Percent (2020 US Census)")) + 
  tm_layout(bg.color = "grey", 
            panel.label.bg.color = "white")
```

```{r}
bernalillo_race
```

## Dot-density maps

```{r}
bernalillo_dots <- bernalillo_race |> 
  as_dot_density(
    value = "value", 
    values_per_dot = 100, 
    group = "variable"
  )
```

```{r}
background_tracts <- filter(bernalillo_race, variable == "Hispanic")

tm_shape(background_tracts) +
  tm_polygons(col = "grey", 
              fill.scale = tm_scale(
                
              ))  +
  tm_shape(bernalillo_dots) +
  tm_dots(col = "variable", palette = "Set1", 
          size = 0.005, title = "1 dot = 100 people") +
  tm_layout(legend.outside = T) +
  tm_title("Race/ethnicity\n2020 Census")
```
